name: Fetch Merged Changes
on:
  workflow_dispatch:
    inputs:
      fromCommit:
        description: 'From Commit (SHA)'
        required: true
      toCommit:
        description: 'To Commit (SHA)'

jobs:
  fetchChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node v16.13.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: 'npm'
      - name: Install NPM dependencies
        working-directory: ./tools/fetch-changelog
        run: npm ci
      - name: Fetch Changes from GitHub API
        working-directory: ./tools/fetch-changelog
        run: |
          node index.js --key=${{ secrets.GITHUB_TOKEN }} --from=${{ github.event.inputs.fromCommit }} --to=${{ github.event.inputs.toCommit }} > changes.md
          echo
          echo "============================================================"
          cat changes.md
          echo "============================================================"
          echo
          echo "You may want to go to https://gist.github.com/ to upload the final changelog"
          echo "The next step will require an url because we can't easily pass multiline strings to actions"
      - uses: actions/upload-artifact@v2
        with:
          name: bitburner_changelog___DRAFT.md
          path: ./tools/fetch-changelog/changes.md
